### PR TITLE
Add CI based on GitHub Actions

### PR DESCRIPTION
**Pull request by mrBliss**

### CODE REVIEW

**Comment by mrBliss** [comment]
I inferred the GHC versions from the bounds on `base`. If we drop some of the older versions, we can drop the `bifunctors` dependency and make the build warning-free (`Data.Monoid` is redundant) without CPP.

**Comment by mrBliss** [comment]
Hmm, https://github.com/actions/setup-haskell is unmaintained but still works. At some point, we'll have to switch to https://github.com/haskell/actions.

**Comment by edsko** [comment]
Good lad :)

**Comment by edsko** [comment]
> I inferred the GHC versions from the bounds on base. If we drop some of the older versions, we can drop the bifunctors dependency and make the build warning-free (Data.Monoid is redundant) without CPP.

Yeah, I guess that might be good thing to do.

**Pull request merged**
